### ISSUE TITLE
Arctic admin causes JS errors in browser logs

### ISSUE THREAD

**Issue by michalzynek** [cprodhomme/arctic_admin#66]
I have error in browser console since I installed arctic admin:

> Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

And not only me I guess:
https://stackoverflow.com/questions/52857201/uncaught-typeerror-cannot-read-property-getboundingclientrect-of-undefined-on

**Comment by wachub** [comment]
- Hi, it seems to occur in this [js file](app/assets/javascripts/arctic_admin/main.js) at two points. 

- In both those cases, the issue seems to be that the tabs array is empty, and there is a null value related exception when the first element of the empty array, is referenced as a DOM object and the getBoundingClientRect() function is called on that.

- From what I understand, it shouldn't break compatibility with the existing code for the width to be initially set to zero and for the getBoundingClientRect() function to be called only where there are elements in the tabs array.

**Comment by michalzynek** [comment]
hello @wachub , thank you for your response

My dirty workaround for now was (in application.html.haml - head section):
```
- if request.url.include? '/admin'
      = javascript_include_tag 'active_admin', 'data-turbolinks-track': 'reload'
```
As indeed, it broke some of my JS files, I do not remember what it was exactly (old times) but I think related to owl-carousel plugin or iziModal.

**Comment by wachub** [comment]
#75 Could you check out this poll request.

**Comment by michalzynek** [comment]
@wachub in my example, the files were not only included on ActiveAdmin module - maybe that was mistake of my configurations somewhere, but above haml is simple HTML that says the JS files from ActiveAdmin should only be included under /admin path.

**Comment by wachub** [comment]
Hi @michalzynek . AFAIK, this bug is a fairly low level one (syntax level), which is independent of the logic/algorithm on top. The only assumption made is that the width can be taken to be zero when the array is empty, which seems consistent for whatever is written on top. I don't think it is likely to blow up anywhere else.
